name: Random Assign Bot

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: actions/checkout@v2
              uses: ./
              with:
                  repo-token: ${{ github.token }}
                  assignees: siddhantdixit