name: 'Auto assign pull request'
on:
  # pull_request:
    # types: [opened, ready_for_review]
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: gerardabello/auto-assign@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          number-of-assignees: 1
          assignee-pool: |
            siddhantdixit
            twentythreeapril
